collections:
  - name: ansible.controller
    version: 4.7.11
  - name: ansible.platform
    version: 2.6.20260306
  - name: ansible.eda
    version: 2.11.0
  - name: kubernetes.core
    version: 6.3.0
  - name: community.general
    version: 12.4.0
  - name: https://github.com/zaskan/demos.utils.git
    type: git
    version: main
  - name: https://github.com/zaskan/ansible_automation_platform.casc.git
    type: git
    version: main
