collections:
  - name: https://github.com/zaskan/demos.utils.git
    type: git
    version: main
  - name: https://github.com/zaskan/ansible_automation_platform.casc.git
    type: git
    version: main
  # - name: ansible.controller
  # - name: ansible.platform
  # - name: ansible.eda
  # - name: kubernetes.core
  # - name: community.general