- name: EDA Listener for Alertmanager and ITSM App - PVC
  hosts: localhost
  sources:
    - name: Listen to Alertmanager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        data_host_path: ""

    - name: itsm-app webhooks
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Get Alertmanager Alerts
      condition: event.alert.labels.alertname == "PVCUsageHigh" and event.alert.status == "firing"
      action:
        run_job_template:
          name: "[JT] Open ITSM Ticket"
          organization: "Default"
          job_args:
            extra_vars:
              title: "{{ event.alert.labels.alertname }} - {{ event.alert.annotations.summary }}"
              description: "{{ event.alert.annotations.description }}"
              date: "{{ event.alert.startsAt }}"
              manifest: "{{ event.alert.labels.manifest }}"
              alert: "{{ event.alert.labels.alertname }}"

    - name: Trigger Remediation for PVCUsageHigh
      condition: >-
        event.payload is defined and event.payload.event == "incident.created" and
        "PVCUsageHigh" in event.payload.incident.title
      action:
        run_workflow_template:
          name: "[WF] Extend Openshift Physical Volume"
          organization: "Default"
          job_args:
            extra_vars:
              incident_id: "{{ event.payload.incident.public_id }}"
              description: "{{ event.payload.incident.description }}"
              message: "PVC extension remediation completed"
