apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-payment-alert
  namespace: payment
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  groups:
    - name: pvc-alerts
      rules:
        - alert: PVCUsageHigh
          #expr: (kubelet_volume_stats_used_bytes{persistentvolumeclaim="payment"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="payment"}) * 100 > 80
          expr: (kubelet_volume_stats_used_bytes{namespace="payment"} / kubelet_volume_stats_capacity_bytes{namespace="payment"}) * 100 > 90
          for: 1s
          labels:
            severity: warning
            itsm_action: open_incident
            manifest: pvc.yaml
          annotations:
            summary: "PVC {{ $labels.persistentvolumeclaim }} usage above 90%" #TODO Beautify these lines
            description: |
              PVC {{ $labels.persistentvolumeclaim }} usage is at {{ printf "%.2f" $value }}%. 