---
- name: Add information to GLPI ticket
  hosts: localhost
  gather_facts: false
  vars:
    glpi_action: add_ticket_task
    glpi_incident_id: "{{ incident_id }}"
    glpi_task_content: >-
      <p>The max number of replicas for the app Payment, has been increased to {{ new_replicas }}.
      Please, check the current value of replicas in the file {{ manifest }} stored in the repository {{ repository }}.</p>
  roles:
    - role: glpi_operations
