---
- name: Add information to ITSM incident
  hosts: localhost
  gather_facts: true
  vars:
    repository: "{{ lookup('env', 'GITEA_HOST') }}/gitea/payment-deploy.git"
  tasks:

    - name: Parse manifest path from incident description
      ansible.builtin.set_fact:
        manifest: "{{ description | regex_search('manifest:\\s*(\\S+)', '\\1') }}"

    - name: Add work note as comment on itsm-app incident
      ansible.builtin.include_role:
        name: demos.utils.itsm_ansible_role
        tasks_from: incident_followups.yml
      vars:
        itsm_api_base_url: "{{ itsm_api_base_url | trim | regex_replace('/$', '') }}"
        itsm_api_user: "{{ itsm_api_user }}"
        itsm_api_password: "{{ itsm_api_password }}"
        itsm_validate_certs: false
        itsm_ansible_role_followups: true
        itsm_incident_by_key:
          run: "{{ incident_id }}"
        itsm_incident_followups:
          - incident_key: run
            comments:
              - body: "{{ message }}. Check the current values in the file {{ manifest[0] }} stored in the repository {{ repository }}"
            close: {}
